name: CI
on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        uses: borales/actions-yarn@v5
        env:
          CI: ''
        with:
          cmd: install

      - name: Build Production Bundle
        uses: borales/actions-yarn@v5
        env:
          CI: ''
        with:
          cmd: build

      - name: Publish to Docker Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          registry: git.sheber.education
          name: sheber-education/front-main/front-main
          username: package_master
          password: Pa).T4WM+4#gBM3

      # Uncomment the following if you want to update the project on the server
      # - name: Update Project on Server
      #   run: |
      #     curl -H "Authorization: Bearer ${{ secrets.WATCHTOWER_TOKEN }}" https://watchtower.kenuki.org/v1/update
